### ISSUE TITLE
OPUS audio not playing on Apple TV

### ISSUE THREAD

**Issue by anyoneyun** [jellyfin/Swiftfin#1150]
### Describe the bug

1. Click on a movie/show with an OPUS audio track
2. No audio is played, jellyfin doesn't transcode

### Application version

1.0.1 (70)

### Where did you install the app from?

App Store

### Device information

Apple TV 4K 2nd Gen

### OS version

17.5.1

### Jellyfin server version

10.9.7

**Comment by UnidentifiedX** [comment]
Also experiencing the same on Swiftfin iOS

### Application version
1.1

### Where did you install the app from?
App Store

### Device information
iPhone 11

### OS version
17.5.1

### Jellyfin server version
10..9.7

**Comment by holow29** [comment]
@UnidentifiedX Can you please give the mediainfo of the file?

**Comment by UnidentifiedX** [comment]
> @UnidentifiedX Can you please give the mediainfo of the file?

![image](https://github.com/user-attachments/assets/1376affc-33ea-4763-8658-40e1caf3acc8)
![image](https://github.com/user-attachments/assets/12f3d845-8d56-4254-85f9-e769f9f1f55e)

Maybe it's unrelated, but my ASS subtitle also doesn't load on Swiftfin either. I can open another issue if this is the case.

**Comment by holow29** [comment]
@anyoneyun Until the tvOS app is updated past 1.0.1 so that the device profile changes take effect, this will remain the case.
@UnidentifiedX I assume you are trying to use the Native player. I have identified that the native player only supports 2 channel Opus. You can see more discussion and a possible patch which I have yet to test here: https://github.com/jellyfin/Swiftfin/issues/1170

**Comment by UnidentifiedX** [comment]
@holow29 Thanks for the reply! Looked through the thread and I've decided to transcode my files to 5.1 AC3. Works fine now, thanks!

Also on a side note, even running stereo opus doesn't produce any audio. Tried with the LegacyStereo audio track as well - doesn't seem to work either. Not sure what is going on here.

**Comment by UnidentifiedX** [comment]
Actually, upon further investigation, I realised that if you add a .sup file to your subtitles the audio track from the video will be gone if you use the Swiftfin player. Extremely weird, gonna open an issue when I have time. This was probably why my OPUS file couldn't play audio and has nothing to do with the codec.

**Comment by smebberson** [comment]
I've also experience issues with two audio tracks; it will just play nothing. I removed one and it worked fine.

**Comment by nds2204** [comment]
I guess this is solved in #1552, It was a regression in VLCKit dependencies, then the bug was also present in VLC Player standalone version.

**Comment by Strit** [comment]
I still have this issue with version 1.3 of Swiftfin on my iPad. No opus audio plays.
