### ISSUE TITLE
Cannot Update Local Server IP in Swiftfin — Only ‘Cancel’ Option Available When IP Changes

### ISSUE THREAD

**Issue by schikulski** [jellyfin/Swiftfin#1521]
### Describe the bug

1. Have a local server with IP 10.0.0.7 working in Swiftfin.
2. Local server changes IP, to for example 10.0.0.8.
3. Adding the new server in "Connect" and under "Local Servers"
4. When clicking the local server (with the new IP) Swiftfin says "Existing Server. Server {name} already exists. Add new URL?"
5. Only option to click is "Cancel". No "Yes", "Apply" or anything. Only possible to click "Cancel".

<img width="648" alt="Image" src="https://github.com/user-attachments/assets/06a5cef9-28c0-475d-b9cd-94cb6b0f13d7" />

### Application version

1.0.1 (70)

### Where did you install the app from?

App Store

### Device information

Apple TV (first gen)

### OS version

tvOS 18.4.1

### Jellyfin server version

10.10.6

**Comment by JPKribs** [comment]
This is resolved in our main branch for tvOS. Our tvOS branch is behind our iOS branch but you can follow our progress towards our next release here:

https://github.com/jellyfin/Swiftfin/discussions/1294

**Comment by GiganticThirstyHerald** [comment]
@schikulski have you found how to bypass this issue? I guess only reinstalling works, right?

**Comment by Janssonn91** [comment]
> This is resolved in our main branch for tvOS. Our tvOS branch is behind our iOS branch but you can follow our progress towards our next release here:
> 
> [#1294](https://github.com/jellyfin/Swiftfin/discussions/1294)

I still receive this issue, and this thread is many months old. Is a new update in the works?

**Comment by JPKribs** [comment]
> a new update in the works?

Yes. That thread is up to date as of today. As things change, I try to keep that in-sync with our current state. It may be a few days off but I update the date as the top as well for tracking when things were last updated.

**Comment by JPKribs** [comment]
This should be resolved in Swiftfin 1.5 which is now available on the App Store!

Please reach out or reopen this issue if you are still experiencing trouble with this item.
