### ISSUE TITLE
SeriesItemView shows seasons which do not exist on the hard drive

### ISSUE THREAD

**Issue by iamnewtogithubhelpme** [jellyfin/SwiftFin#45]
In the latest version 36, it shows seasons of a show which don't even exist. This issue wasn't there in version 33. Also going inside any of those seasons (which don't have any episode) immediately crashes the app.

**Comment by acvigue** [comment]
should be fixed

**Comment by iamnewtogithubhelpme** [comment]
Does look like this if fixed. Still see non existent seasons.

**Comment by acvigue** [comment]
do you have empty season folders

**Comment by iamnewtogithubhelpme** [comment]
> do you have empty season folders
> […](#)
> Sent from my iPhone
> On Jun 10, 2021, at 10:30 PM, iamnewtogithubhelpme ***@***.***> wrote: ﻿ Does look like this if fixed. Still see non existent seasons. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

No I don't.

**Comment by acvigue** [comment]
do they show up in jellyfin web

**Comment by iamnewtogithubhelpme** [comment]
Yes they do with a tick mark against the season alresdy there. Also in the app store version of jellyfin app also it shows up. Even on firestick too. Feeling like this is expected?

Episodes that don't exist on hdd have a "Missing" ribbon on one corner. Cannot verify this in the build 40 as it keeps crashing (going inside season). 

It would be great if we can get a small ribbon with count of episodes in each season on one corner of season poster or something.
