### ISSUE TITLE
4K HEVC Playback not working on iPhone Xr, iPad 7

### ISSUE THREAD

**Issue by SlaterTh90** [jellyfin/SwiftFin#67]
I am currently testing the app with my devices. I have an iPad 7th Gen and an iPhone Xr, both running the atm newest ios/ipadOS release (14.6).

On both devices, AV1 playback does not seem to work. When trying to play back the "Summer Nature" 4k file from (https://www.elecard.com/videos), playback does not start. On the server side I see that the app is requesting direct play, which I would assume is correct since the VLC backend should support AV1. Same thing happens with the 1080p version of that file.

I also cannot play 4k HEVC files.
Media info of one affected file:
```
Title4K HEVC HDR
CodecHEVC
ProfileMain 10
Level153
Resolution3840x2160
Aspect ratio16:9
InterlacedNo
Framerate23.976025
Bitrate63173 kbps
Video rangeHDR
Color spacebt2020nc
Color transfersmpte2084
Color primariesbt2020
Pixel formatyuv420p10le
Ref frames1
```

This movie can be direct played by the iphone using the web-app with the native player option enabled.

Anyways, thanks for the amazing work so far!

**Comment by acvigue** [comment]
vlc does not support av1.

hevc 4k should be supported.

**Comment by acvigue** [comment]
can you run `mediainfo` on the affected file?

**Comment by SlaterTh90** [comment]
Thanks for the quick response, the AV1 files returns this:

4k:
`
Stream2_AV1_4K_22.7mbps
Containerwebm
Path/media/Movies/AV1_Test/Stream2_AV1_4K_22.7mbps.webm
Size390 MB
Video
Title4K AV1 SDR
CodecAV1
ProfileMain
Level12
Resolution3840x2160
Aspect ratio16:9
InterlacedNo
Framerate25
Bitrate22728 kbps
Video rangeSDR
Pixel formatyuv420p
Ref frames1
`

1080p:
`
Stream2_AV1_HD_6.8mbps
Containerwebm
Path/media/Movies/AV1_Test_1080p/Stream2_AV1_HD_6.8mbps.webm
Size117 MB
Video
Title1080p AV1 SDR
CodecAV1
ProfileMain
Level8
Resolution1920x1080
Aspect ratio16:9
InterlacedNo
Framerate25
Bitrate6793 kbps
Video rangeSDR
Pixel formatyuv420p
Ref frames1
`

**Comment by acvigue** [comment]
i meant of the hevc files.
av1 is not and will not be supported until dav1d has hw decoding capabilities

**Comment by SlaterTh90** [comment]
Ok, that would be the one in the first post. Here is a different one that also does not work:

`
S01E01
Containermkv
Path/media/Shows/Planet Earth II/S01E01.mkv
Size17866 MB
Video
Title4K HEVC HDR
CodecHEVC
ProfileMain 10
Level153
Resolution3840x2160
Aspect ratio16:9
InterlacedNo
Framerate23.976025
Bitrate47849 kbps
Video rangeHDR
Color spacebt2020nc
Color transfersmpte2084
Color primariesbt2020
Pixel formatyuv420p10le
Ref frames1
Audio
TitleSurround 7.1 - Deu - DTS - Default
Languagedeu
CodecDTS
ProfileDTS-HD MA
Layout7.1
Channels8 ch
Bitrate2754 kbps
Sample rate48000 Hz
Bit depth16 bit
DefaultYes
Audio
TitleSurround 5.1 - Deu - DTS
Languagedeu
CodecDTS
ProfileDTS
Layout5.1
Channels6 ch
Bitrate1536 kbps
Sample rate48000 Hz
DefaultNo
Audio
TitleSurround 5.1 - Eng - Dolby Digital
Languageeng
CodecAC3
Layout5.1
Channels6 ch
Bitrate640 kbps
Sample rate48000 Hz
DefaultNo
`

For AV1, its fine if its not supported. However, the app should request a transcode in that case, like the webapp does, right?

**Comment by acvigue** [comment]
> For AV1, its fine if its not supported. However, the app should request a transcode in that case, like the webapp does, right?
yes - the app does not advertise AV1 as a supported codec, so any issues arising from AV1 being sent as direct play are likely unrelated to the app.

I will look into the HEVC files not playing.
is it

- playing but with transcoding?
- or not playing but trying to direct play.

**Comment by SlaterTh90** [comment]
It is not playing, but it is trying to direct play. On the server side it says the source file is entirely compatible, so not even audio transcoding is happening. Happens for all the 4K HEVC files I have.

**Comment by iamnewtogithubhelpme** [comment]
I have had issues with some x264 videos too which are eligible for direct play but I am stuck on Loading screen when playing such videos. Sometimes video may start after 2 min but in many cases it won't.

**Comment by SlaterTh90** [comment]
> I have had issues with some x264 videos too which are eligible for direct play but I am stuck on Loading screen when playing such videos. Sometimes video may start after 2 min but in many cases it won't.

I have this problem too, but only with a single x264 blu ray rip, all others work flawlessly. It has the following behavior:

> Jellyfin Web with Safari on iOS: Plays back, but framerate is completely broken (a lot of stutter)

> Jellyfin iOS Web App: Same as Safari

> Jellyfin iOS Web App with native Player: Plays back without any problems

> SwiftFin: Loads forever

However I am not sure if this is a bug of swiftfin or a general iOS problem, that’s why I had not reported it yet.

**Comment by acvigue** [comment]
> I have had issues with some x264 videos too which are eligible for direct play but I am stuck on Loading screen when playing such videos. Sometimes video may start after 2 min but in many cases it won't.

unrelated - subtitle issue. resolved in Matrix.

**Comment by acvigue** [comment]
> > I have had issues with some x264 videos too which are eligible for direct play but I am stuck on Loading screen when playing such videos. Sometimes video may start after 2 min but in many cases it won't.
> 
> I have this problem too, but only with a single x264 blu ray rip, all others work flawlessly. It has the following behavior:
> 
> > Jellyfin Web with Safari on iOS: Plays back, but framerate is completely broken (a lot of stutter)
> 
> > Jellyfin iOS Web App: Same as Safari
> 
> > Jellyfin iOS Web App with native Player: Plays back without any problems
> 
> > SwiftFin: Loads forever
> 
> However I am not sure if this is a bug of swiftfin or a general iOS problem, that’s why I had not reported it yet.

i cannot help as your reports are not mediainfo reports.

please submit a mediainfo report.

it will look like this:
```bash
aidenvigue@zeus:/media/production/Movies/6 Underground (2019)$ mediainfo 6\ Underground\ \(2019\)\ WEBDL-2160p.mkv 
General
Unique ID                                : 208791545452323396748913150113405191788 (0x9D13C9F8C4AA2FE31919D02622CFC66C)
Complete name                            : 6 Underground (2019) WEBDL-2160p.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 15.0 GiB
Duration                                 : 2 h 8 min
Overall bit rate                         : 16.6 Mb/s
Writing application                      : Lavf59.2.100
Writing library                          : Lavf59.2.100
ErrorDetectionType                       : Per level 1

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 8 min
Bit rate                                 : 15.9 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 23.976 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.080
Stream size                              : 14.3 GiB (95%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1477 cd/m2
Maximum Frame-Average Light Level        : 446 cd/m2

Audio
ID                                       : 2
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
Codec ID                                 : A_EAC3
Duration                                 : 2 h 8 min
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Bit depth                                : 32 bits
Compression mode                         : Lossy
Stream size                              : 708 MiB (5%)
Title                                    : English
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
Complexity index                         : 16
Number of dynamic objects                : 15
Bed channel count                        : 1 channel
Bed channel configuration                : LFE


aidenvigue@zeus:/media/production/Movies/6 Underground (2019)$ 
```

**Comment by SlaterTh90** [comment]
Sorry for taking so long. I did not know about the mediainfo tool. 

Here is the extracted info:

<details>
  <summary>Non-Working 4k HEVC HDR:</summary>

```
General
Unique ID                                : 186832425160457310512436049996065147485 (0x8C8E9DC09662C72A21A7645D46860A5D)
Complete name                            : Alien (1979) - [Directors Cut].mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 51.1 GiB
Duration                                 : 1 h 55 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 63.2 Mb/s
Movie name                               : ALIEN
Encoded date                             : UTC 2021-05-29 10:39:06
Writing application                      : MakeMKV v1.16.3 linux(x64-release)
Writing library                          : libmakemkv v1.16.3 (1.3.10/1.5.2) x86_64-unknown-linux-gnu

Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : SMPTE ST 2094 App 4, Version 1, HDR10+ Profile A compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 1 h 55 min
Bit rate                                 : 49.3 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.248
Stream size                              : 39.9 GiB (78%)
Language                                 : English
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 1000 cd/m2
Original source medium                   : Blu-ray

Audio #1
ID                                       : 2
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 1 h 55 min
Bit rate mode                            : Variable
Bit rate                                 : 3 453 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 2.79 GiB (5%)
Title                                    : Surround 5.1
Language                                 : English
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray

Audio #2
ID                                       : 3
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 1 h 55 min
Bit rate mode                            : Constant
Bit rate                                 : 1 509 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 1.22 GiB (2%)
Title                                    : Surround 5.1
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #3
ID                                       : 4
ID in the original source medium         : 4354 (0x1102)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 1 h 55 min
Bit rate mode                            : Variable
Bit rate                                 : 2 000 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 1.62 GiB (3%)
Title                                    : Stereo
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #4
ID                                       : 5
ID in the original source medium         : 4354 (0x1102)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 1 h 55 min
Bit rate mode                            : Constant
Bit rate                                 : 1 509 kb/s
Channel(s)                               : 2 channels
Channel layout                           : Lt Rt
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 1.22 GiB (2%)
Title                                    : Stereo
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #5
ID                                       : 6
ID in the original source medium         : 4355 (0x1103)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 55 min
Bit rate mode                            : Constant
Bit rate                                 : 448 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 371 MiB (1%)
Title                                    : Surround 5.1
Language                                 : Spanish
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #6
ID                                       : 7
ID in the original source medium         : 4356 (0x1104)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 1 h 55 min
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 636 MiB (1%)
Title                                    : Surround 5.1
Language                                 : French
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #7
ID                                       : 8
ID in the original source medium         : 4357 (0x1105)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 1 h 55 min
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 636 MiB (1%)
Title                                    : Surround 5.1
Language                                 : Spanish
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #8
ID                                       : 9
ID in the original source medium         : 4358 (0x1106)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 1 h 55 min
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 636 MiB (1%)
Title                                    : Surround 5.1
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #9
ID                                       : 10
ID in the original source medium         : 4359 (0x1107)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 1 h 55 min
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 636 MiB (1%)
Title                                    : Surround 5.1
Language                                 : Italian
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #10
ID                                       : 11
ID in the original source medium         : 4362 (0x110A)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 55 min
Bit rate mode                            : Constant
Bit rate                                 : 448 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 371 MiB (1%)
Title                                    : Surround 5.1
Language                                 : Czech
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #11
ID                                       : 12
ID in the original source medium         : 4363 (0x110B)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 55 min
Bit rate mode                            : Constant
Bit rate                                 : 448 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 371 MiB (1%)
Title                                    : Surround 5.1
Language                                 : Thai
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #12
ID                                       : 13
ID in the original source medium         : 4364 (0x110C)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 55 min
Bit rate mode                            : Constant
Bit rate                                 : 224 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 186 MiB (0%)
Title                                    : Stereo
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #1
ID                                       : 14
ID in the original source medium         : 4768 (0x12A0)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 49 min
Bit rate                                 : 31.2 kb/s
Count of elements                        : 2101
Stream size                              : 24.6 MiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #2
ID                                       : 16
ID in the original source medium         : 4769 (0x12A1)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 53 min
Bit rate                                 : 24.3 kb/s
Count of elements                        : 1690
Stream size                              : 19.7 MiB (0%)
Language                                 : Spanish
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #3
ID                                       : 18
ID in the original source medium         : 4770 (0x12A2)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 53 min
Bit rate                                 : 21.0 kb/s
Count of elements                        : 1404
Stream size                              : 17.1 MiB (0%)
Language                                 : French
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #4
ID                                       : 19
ID in the original source medium         : 4770 (0x12A2)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 53 min
Bit rate                                 : 282 b/s
Count of elements                        : 14
Stream size                              : 235 KiB (0%)
Language                                 : French
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #5
ID                                       : 20
ID in the original source medium         : 4771 (0x12A3)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 50 min
Bit rate                                 : 22.7 kb/s
Count of elements                        : 1590
Stream size                              : 18.0 MiB (0%)
Language                                 : Spanish
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #6
ID                                       : 21
ID in the original source medium         : 4771 (0x12A3)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 39 min
Bit rate                                 : 234 b/s
Count of elements                        : 12
Stream size                              : 171 KiB (0%)
Language                                 : Spanish
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #7
ID                                       : 22
ID in the original source medium         : 4772 (0x12A4)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 53 min
Bit rate                                 : 19.5 kb/s
Count of elements                        : 1532
Stream size                              : 15.8 MiB (0%)
Language                                 : Danish
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #8
ID                                       : 24
ID in the original source medium         : 4773 (0x12A5)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 50 min
Bit rate                                 : 18.8 kb/s
Count of elements                        : 1262
Stream size                              : 14.8 MiB (0%)
Language                                 : Dutch
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #9
ID                                       : 26
ID in the original source medium         : 4774 (0x12A6)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 50 min
Bit rate                                 : 22.2 kb/s
Count of elements                        : 1417
Stream size                              : 17.6 MiB (0%)
Language                                 : Finnish
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #10
ID                                       : 28
ID in the original source medium         : 4775 (0x12A7)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 50 min
Bit rate                                 : 25.0 kb/s
Count of elements                        : 1582
Stream size                              : 19.8 MiB (0%)
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #11
ID                                       : 29
ID in the original source medium         : 4775 (0x12A7)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 39 min
Bit rate                                 : 294 b/s
Count of elements                        : 16
Stream size                              : 215 KiB (0%)
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #12
ID                                       : 30
ID in the original source medium         : 4776 (0x12A8)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 50 min
Bit rate                                 : 22.4 kb/s
Count of elements                        : 1553
Stream size                              : 17.7 MiB (0%)
Language                                 : Italian
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #13
ID                                       : 31
ID in the original source medium         : 4776 (0x12A8)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 39 min
Bit rate                                 : 338 b/s
Count of elements                        : 16
Stream size                              : 247 KiB (0%)
Language                                 : Italian
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #14
ID                                       : 32
ID in the original source medium         : 4779 (0x12AB)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 50 min
Bit rate                                 : 21.2 kb/s
Count of elements                        : 1557
Stream size                              : 16.8 MiB (0%)
Language                                 : Norwegian
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #15
ID                                       : 34
ID in the original source medium         : 4780 (0x12AC)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 50 min
Bit rate                                 : 21.3 kb/s
Count of elements                        : 1525
Stream size                              : 16.9 MiB (0%)
Language                                 : Swedish
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #16
ID                                       : 36
ID in the original source medium         : 4781 (0x12AD)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 50 min
Bit rate                                 : 16.0 kb/s
Count of elements                        : 1570
Stream size                              : 12.7 MiB (0%)
Language                                 : Chinese
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #17
ID                                       : 38
ID in the original source medium         : 4782 (0x12AE)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 50 min
Bit rate                                 : 19.8 kb/s
Count of elements                        : 1488
Stream size                              : 15.7 MiB (0%)
Language                                 : Czech
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #18
ID                                       : 39
ID in the original source medium         : 4782 (0x12AE)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 23 min
Bit rate                                 : 1 089 b/s
Count of elements                        : 64
Stream size                              : 663 KiB (0%)
Language                                 : Czech
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #19
ID                                       : 40
ID in the original source medium         : 4783 (0x12AF)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 50 min
Bit rate                                 : 15.3 kb/s
Count of elements                        : 1557
Stream size                              : 12.1 MiB (0%)
Language                                 : Korean
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #20
ID                                       : 42
ID in the original source medium         : 4784 (0x12B0)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 50 min
Bit rate                                 : 14.8 kb/s
Count of elements                        : 1579
Stream size                              : 11.7 MiB (0%)
Language                                 : Chinese
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #21
ID                                       : 44
ID in the original source medium         : 4785 (0x12B1)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 53 min
Bit rate                                 : 19.8 kb/s
Count of elements                        : 1413
Stream size                              : 16.1 MiB (0%)
Language                                 : Polish
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #22
ID                                       : 46
ID in the original source medium         : 4786 (0x12B2)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 53 min
Bit rate                                 : 17.6 kb/s
Count of elements                        : 1570
Stream size                              : 14.4 MiB (0%)
Language                                 : Thai
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #23
ID                                       : 47
ID in the original source medium         : 4786 (0x12B2)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 51 min
Bit rate                                 : 1 273 b/s
Count of elements                        : 102
Stream size                              : 1.02 MiB (0%)
Language                                 : Thai
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #24
ID                                       : 48
ID in the original source medium         : 4787 (0x12B3)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 55 min
Bit rate                                 : 84.7 kb/s
Count of elements                        : 3801
Stream size                              : 70.0 MiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #25
ID                                       : 50
ID in the original source medium         : 4788 (0x12B4)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 55 min
Bit rate                                 : 73.5 kb/s
Count of elements                        : 3704
Stream size                              : 60.8 MiB (0%)
Language                                 : French
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #26
ID                                       : 52
ID in the original source medium         : 4789 (0x12B5)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 55 min
Bit rate                                 : 70.3 kb/s
Count of elements                        : 3685
Stream size                              : 58.1 MiB (0%)
Language                                 : Spanish
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #27
ID                                       : 54
ID in the original source medium         : 4790 (0x12B6)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 55 min
Bit rate                                 : 85.0 kb/s
Count of elements                        : 3884
Stream size                              : 70.2 MiB (0%)
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #28
ID                                       : 56
ID in the original source medium         : 4791 (0x12B7)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 55 min
Bit rate                                 : 75.5 kb/s
Count of elements                        : 3673
Stream size                              : 62.4 MiB (0%)
Language                                 : Italian
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Menu
00:00:00.000                             : en:Chapter 01
00:01:59.369                             : en:Chapter 02
00:04:38.111                             : en:Chapter 03
00:07:53.681                             : en:Chapter 04
00:09:08.506                             : en:Chapter 05
00:12:38.174                             : en:Chapter 06
00:14:14.103                             : en:Chapter 07
00:20:03.911                             : en:Chapter 08
00:23:20.649                             : en:Chapter 09
00:25:03.251                             : en:Chapter 10
00:27:48.541                             : en:Chapter 11
00:31:49.741                             : en:Chapter 12
00:35:30.711                             : en:Chapter 13
00:37:03.221                             : en:Chapter 14
00:40:31.887                             : en:Chapter 15
00:43:24.518                             : en:Chapter 16
00:47:26.301                             : en:Chapter 17
00:50:04.126                             : en:Chapter 18
00:51:42.307                             : en:Chapter 19
00:54:22.676                             : en:Chapter 20
00:58:59.744                             : en:Chapter 21
01:00:24.871                             : en:Chapter 22
01:03:34.310                             : en:Chapter 23
01:08:16.717                             : en:Chapter 24
01:10:02.948                             : en:Chapter 25
01:12:50.407                             : en:Chapter 26
01:14:31.925                             : en:Chapter 27
01:17:12.711                             : en:Chapter 28
01:19:00.652                             : en:Chapter 29
01:22:32.030                             : en:Chapter 30
01:26:37.233                             : en:Chapter 31
01:28:47.572                             : en:Chapter 32
01:30:46.482                             : en:Chapter 33
01:32:37.760                             : en:Chapter 34
01:34:21.781                             : en:Chapter 35
01:37:42.815                             : en:Chapter 36
01:39:12.196                             : en:Chapter 37
01:43:26.241                             : en:Chapter 38
01:46:15.744                             : en:Chapter 39
01:53:03.610                             : en:Chapter 40
```
</details>

<details>
  <summary>Non-Working 4k HEVC HDR:</summary>

```
General
Unique ID                                : 280787355550888966543122295421055279922 (0xD33DAD7797811C6180ECDAF55E842332)
Complete name                            : S01E01.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 17.4 GiB
Duration                                 : 52 min 12 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 47.8 Mb/s
Movie name                               : PLANET ERDE II: eine erde - viele welten - Disc 1 - UHD
Encoded date                             : UTC 2021-05-29 14:10:59
Writing application                      : MakeMKV v1.16.3 linux(x64-release)
Writing library                          : libmakemkv v1.16.3 (1.3.10/1.5.2) x86_64-unknown-linux-gnu

Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 52 min 12 s
Bit rate                                 : 42.9 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.216
Stream size                              : 15.7 GiB (90%)
Language                                 : English
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : R: x=0.000000 y=0.000000, G: x=0.000000 y=0.000000, B: x=0.000000 y=0.000000, White point: x=0.000000 y=0.000000
Mastering display luminance              : min: 0.0000 cd/m2, max: 0 cd/m2
Original source medium                   : Blu-ray

Audio #1
ID                                       : 2
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 52 min 12 s
Bit rate mode                            : Variable
Bit rate                                 : 2 755 kb/s
Channel(s)                               : 8 channels
Channel layout                           : C L R LFE Lb Rb Lss Rss
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 1.00 GiB (6%)
Title                                    : Surround 7.1
Language                                 : German
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray

Audio #2
ID                                       : 3
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 52 min 12 s
Bit rate mode                            : Constant
Bit rate                                 : 1 509 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 563 MiB (3%)
Title                                    : Surround 5.1
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #3
ID                                       : 4
ID in the original source medium         : 4353 (0x1101)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 52 min 12 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 239 MiB (1%)
Title                                    : Surround 5.1
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Menu
00:00:00.000                             : de:Chapter 01
00:12:08.185                             : de:Chapter 02
00:20:35.734                             : de:Chapter 03
00:31:02.902                             : de:Chapter 04
00:41:59.600                             : de:Chapter 05


```
</details>

<details>
  <summary>Non-Working h264 (the one that loads forever but works with the old app):</summary>

```
General
Unique ID                                : 306692399443682473883230418153183992053 (0xE6BACEBD97BF1CE370F3BF0FBFE158F5)
Complete name                            : S01E01.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 5.03 GiB
Duration                                 : 24 min 30 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 29.4 Mb/s
Encoded date                             : UTC 2021-05-28 16:06:46
Writing application                      : mkvmerge v57.0.0 ('Till The End') 64-bit
Writing library                          : libebml v1.4.2 + libmatroska v1.6.4

Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 24 min 30 s
Bit rate mode                            : Constant
Bit rate                                 : 21.9 Mb/s
Nominal bit rate                         : 31.5 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.441
Stream size                              : 3.76 GiB (75%)
Language                                 : English
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Original source medium                   : Blu-ray

Audio #1
ID                                       : 2
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 24 min 30 s
Bit rate mode                            : Variable
Bit rate                                 : 2 043 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 358 MiB (7%)
Title                                    : Surround 5.1
Language                                 : German
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray

Audio #2
ID                                       : 3
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 24 min 30 s
Bit rate mode                            : Constant
Bit rate                                 : 1 509 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 264 MiB (5%)
Title                                    : Surround 5.1
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #3
ID                                       : 4
ID in the original source medium         : 4353 (0x1101)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 24 min 30 s
Bit rate mode                            : Variable
Bit rate                                 : 2 349 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 412 MiB (8%)
Title                                    : Surround 5.1
Language                                 : Japanese
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #4
ID                                       : 5
ID in the original source medium         : 4353 (0x1101)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 24 min 30 s
Bit rate mode                            : Constant
Bit rate                                 : 1 509 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 264 MiB (5%)
Title                                    : Surround 5.1
Language                                 : Japanese
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #1
ID                                       : 6
ID in the original source medium         : 4608 (0x1200)
Format                                   : PGS
Muxing mode                              : zlib
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 18 min 57 s
Bit rate                                 : 1 106 b/s
Count of elements                        : 14
Stream size                              : 154 KiB (0%)
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #2
ID                                       : 7
ID in the original source medium         : 4609 (0x1201)
Format                                   : PGS
Muxing mode                              : zlib
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 22 min 28 s
Bit rate                                 : 36.4 kb/s
Count of elements                        : 394
Stream size                              : 5.86 MiB (0%)
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Menu
00:00:00.000                             : en:Chapter 01
00:01:30.423                             : en:Chapter 02
00:10:03.102                             : en:Chapter 03


```
</details>

**Comment by acvigue** [comment]
does #3 work in 50?

**Comment by SlaterTh90** [comment]
> does example 3 work in build 50?

Yes, at least on the iPhone it works perfectly now! I have to test the tablet later.

**Comment by SlaterTh90** [comment]
Tested with the iPad now, the player rotates 180 degrees when starting playback (so its upside down), but it does play the previously broken h264 file.

**Comment by acvigue** [comment]
should be fixed in either 50 or 53.

**Comment by iamnewtogithubhelpme** [comment]
I have the version 55 on iPad 8th Gen and still cannot play HEVC. As soon as I Click Play, the video screen without any actual video comes for fraction of a second and I am back to screen where episode information is there. Here is the mediainfo  of the file..

```

(root@DietPi:/mnt/seagatehdd/Media/TV Shows/30 Rock/Season 2# mediainfo '30 Rock (2005) - S02E12 - Subway Hero (1080p BluRay x265 Silence).mkv'
General
Unique ID                                : 22354598085675356590489556727693813357 (0x10D156C7B51DAE69AAAA35A36D8FA66D)
Complete name                            : 30 Rock (2005) - S02E12 - Subway Hero (1080p BluRay x265 Silence).mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 677 MiB
Duration                                 : 21 min 19 s
Overall bit rate                         : 4 438 kb/s
Encoded date                             : UTC 2020-05-23 00:40:56
Writing application                      : mkvmerge v20.0.0 ('I Am The Sun') 64-bit
Writing library                          : libebml v1.3.5 + libmatroska v1.4.8
Writing frontend                         : StaxRip v1.7.0.6

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L4@Main
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 21 min 19 s
Bit rate                                 : 3 779 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.076
Stream size                              : 576 MiB (85%)
Writing library                          : x265 3.3+10-g08d895bb6:[Windows][GCC 10.0.1][64 bit] 10bit
Encoding settings                        : cpuid=1111039 / frame-threads=4 / numa-pools=16 / wpp / no-pmode / no-pme / no-psnr / no-ssim / log-level=2 / input-csp=1 / input-res=1920x1080 / interlace=0 / total-frames=30673 / level-idc=0 / high-tier=1 / uhd-bd=0 / ref=5 / no-allow-non-conformance / no-repeat-headers / annexb / no-aud / no-hrd / info / hash=0 / no-temporal-layers / open-gop / min-keyint=23 / keyint=250 / gop-lookahead=0 / bframes=8 / b-adapt=2 / b-pyramid / bframe-bias=0 / rc-lookahead=80 / lookahead-slices=4 / scenecut=40 / hist-scenecut=0 / radl=0 / no-splice / no-intra-refresh / ctu=64 / min-cu-size=8 / no-rect / no-amp / max-tu-size=32 / tu-inter-depth=1 / tu-intra-depth=1 / limit-tu=0 / rdoq-level=2 / dynamic-rd=0.00 / no-ssim-rd / signhide / no-tskip / nr-intra=0 / nr-inter=0 / no-constrained-intra / no-strong-intra-smoothing / max-merge=3 / limit-refs=3 / limit-modes / me=3 / subme=5 / merange=57 / temporal-mvp / no-frame-dup / no-hme / weightp / no-weightb / no-analyze-src-pics / deblock=-3:-3 / no-sao / no-sao-non-deblock / rd=4 / selective-sao=0 / no-early-skip / rskip / no-fast-intra / no-tskip-fast / no-cu-lossless / no-b-intra / no-splitrd-skip / rdpenalty=0 / psy-rd=2.00 / psy-rdoq=1.00 / no-rd-refine / no-lossless / cbqpoffs=0 / crqpoffs=0 / rc=crf / crf=23.0 / qcomp=0.60 / qpstep=4 / stats-write=0 / stats-read=0 / ipratio=1.40 / pbratio=1.30 / aq-mode=3 / aq-strength=1.00 / cutree / zone-count=0 / no-strict-cbr / qg-size=32 / no-rc-grain / qpmax=69 / qpmin=0 / no-const-vbv / sar=0 / overscan=0 / videoformat=5 / range=0 / colorprim=2 / transfer=2 / colormatrix=2 / chromaloc=0 / display-window=0 / cll=0,0 / min-luma=0 / max-luma=1023 / log2-max-poc-lsb=8 / vui-timing-info / vui-hrd-info / slices=1 / no-opt-qp-pps / no-opt-ref-list-length-pps / no-multi-pass-opt-rps / scenecut-bias=0.05 / hist-threshold=0.01 / no-opt-cu-delta-qp / no-aq-motion / no-hdr10 / no-hdr10-opt / no-dhdr10-opt / no-idr-recovery-sei / analysis-reuse-level=0 / analysis-save-reuse-level=0 / analysis-load-reuse-level=0 / scale-factor=0 / refine-intra=0 / refine-inter=0 / refine-mv=1 / refine-ctu-distortion=0 / no-limit-sao / ctu-info=0 / no-lowpass-dct / refine-analysis-type=0 / copy-pic=1 / max-ausize-factor=1.0 / no-dynamic-refine / no-single-sei / no-hevc-aq / no-svt / no-field / qp-adaptation-range=1.00 / no-scenecut-aware-qpconformance-window-offsets / right=0 / bottom=0 / decoder-max-rate=0
Default                                  : Yes
Forced                                   : No

Audio #1
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 21 min 19 s
Bit rate                                 : 576 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 20 ms
Stream size                              : 86.2 MiB (13%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : AAC LC SBR
Format/Info                              : Advanced Audio Codec Low Complexity with Spectral Band Replication
Commercial name                          : HE-AAC
Format settings                          : Explicit
Codec ID                                 : A_AAC-2
Duration                                 : 21 min 19 s
Bit rate                                 : 80.0 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 23.438 FPS (2048 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 40 ms
Stream size                              : 12.2 MiB (2%)
Title                                    : Commentary
Language                                 : English
Default                                  : No
Forced                                   : No

Text
ID                                       : 4
Format                                   : PGS
Muxing mode                              : zlib
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 20 min 38 s
Bit rate                                 : 57.4 kb/s
Count of elements                        : 1183
Stream size                              : 8.48 MiB (1%)
Language                                 : English
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:Chapter 01
00:02:02.455                             : en:Chapter 02
00:09:01.374                             : en:Chapter 03
00:20:39.780                             : en:Chapter 04

```
