### ISSUE TITLE
Multiple Users - Logged Out Between Sessions [TVOS]

### ISSUE THREAD

**Issue by Jpkribs** [jellyfin/Swiftfin#776]
I can't get this trigger 100% of the time but I think I narrowed it down to having multiple users on the AppleTV. Since adding another user profile on the AppleTV, all saved Jellyfin users will get wiped after the TV goes to sleep or reboots.

I believe this is related to how session data is stored since this only started once I added other users. On another AppleTV, I have a single user and I have not experienced this issue (yet). I could be totally off base but my if my guess right I think this could be resolved by:

https://github.com/jellyfin/Swiftfin/pull/661

https://github.com/jellyfin/Swiftfin/issues/258

**Comment by holow29** [comment]
I haven't experienced this with multiple tvOS users. However, I haven't added more than one Jellyfin user.

**Comment by extraslute** [comment]
I have experienced being logged out on a daily basis on my Apple TV 4K regardless of if there are multiple users or not. This doesn’t happen on my android tv nor any Rokus.

**Comment by Jpkribs** [comment]
> I haven't experienced this with multiple tvOS users. However, I haven't added more than one Jellyfin user.

The multiple TVOS users could be a red herring. That's just when I started seeing it. I know other people who get this regardless of TVOS users.

Is there a way to collect TVOS logs that I could help look at/provide to better understand this?

**Comment by LePips** [comment]
Sadly no logs would help, but I can investigate.

**Comment by Jpkribs** [comment]
> Sadly no logs would help, but I can investigate.

Thank you! I don't know if it changes anything but it's a [2nd Gen 4K](https://support.apple.com/kb/SP845?viewlocale=en_US&locale=en_US)

Since there is one that was impacted and one that is not, I've been racking my brain thinking what the difference between them could be. The only other thing I could think of is that the one that gets logged out also has Infuse logged into the same server. I'm not sure how that would make a difference. Just hoping maybe something there might help!

**Comment by IceHawk66** [comment]
> I have experienced being logged out on a daily basis on my Apple TV 4K regardless of if there are multiple users or not. This doesn’t happen on my android tv nor any Rokus.

I'm facing the same error on my apple tv 4k. Logged in yesterday (again) and I have no server today. Have to enter server + credentials again.

**Comment by technicallymarv** [comment]
I have the same issue as well, have Swiftfin installed on 3 apple tv's with accounts for myself my wife and my kids and it seems almost daily the accounts get wiped and I have to reconnect to the server and login again.

**Comment by bombyy** [comment]
Same issue for me.
My partner has an AppleTV 4K (1st Gen) and we basically get logged out every day.

**Comment by Raphty** [comment]
Thanks for this great tvOS app, but yes I have the same issue as the other on my 1st gen 4k

**Comment by LePips** [comment]
Apologies that I haven't been able to investigate, I see that this is a pressing issue. I'll take a look at this soon.

**Comment by dannycab** [comment]
This occurs on each Apple TV that I have of various models. It's too bad because Swiftfin is miles faster to load and navigate compared to Infuse. Just a better app IMO.

**Comment by adavidzh** [comment]
I’m observing the same thing.
Is there information needed to help debug this?

**Comment by amochkin** [comment]
Same thing. Server shows multiple logged in sessions from that box. Apple TV 4K.

**Comment by pumax15** [comment]
I’m still having this same issue as well. App is great, but frustrating constantly having to input credentials over and over.

**Comment by i-am-the-arm** [comment]
Same problem, I have to sign in each time I open the app. I'm using the following:

**AppleTV**
Model: A1625
tvOS: 16.5

**Jellyfin**
Version: 10.8.3
Operating System: Linux
Architecture: X64

**Comment by IzaacJ** [comment]
Same issue here on our 4K 1st Gen On 16.5. We have multiple AppleIDs on it, but mainly using my AppleID, and we also have 6 users configured in Jellyfin.
Server info:
Version: 10.8.10
Operating System: Linux
Architecture: x64

**Comment by ghost** [comment]
Family members are also experiencing this bug! Looking forward to a resolution!

**Comment by Esthreel** [comment]
I have the same issue. My login / server info is not being saved on tvOS. Any suggestions?

**Comment by extraslute** [comment]
I'd like to comment on here that I've continued to experience this for several months. Jellyfin kicks off any users signed into an Apple TV after 1 day and sometimes even after a few hours. It's hot and miss. Doesn't sign out any Rokus, Android TVs, or iOS devices though.

**Comment by KurzweilTV** [comment]
Just adding a +1 here. I don't know of any specific trigger, but I know I won't stay logged in for more than a day or so at most.

**Comment by jet082** [comment]
Adding my voice in too! Relatives can't use the service at all because of the daily login requirement.

**Comment by ScoobyDoo27** [comment]
I am having the same issue as well. I am using a 1st and 2nd gen Apple TV 4K and my server is installed via docker on a NAS.

**Comment by iinkfish** [comment]
Happens with me too. It's just with one account though, after a certain period of time, usually a day, get logged out and I have to enter everything again including the ip address/domain

**Comment by Jpkribs** [comment]
As an update, I no longer experience this issue after uninstalling Infuse. Could there be something there?

Does anyone see this issue on an AppleTV where Infuse is not installed? 

This could be a total coincidence but I thought maybe it could be related.

**Comment by Nicxe** [comment]
Same here, I need to add a server and log in every time.

**Comment by BDub38** [comment]
Glad to find this issue....this has been driving me crazy and I couldn't figure out what the issue was.  Hoping to see a fix soon!!

**Comment by totally-a-human** [comment]
For anyone experiencing issues how have you logged in? I used to have this issue when logging in with a password but after I logged in with [quick connect](https://jellyfin.org/docs/general/server/quick-connect/) a few days ago it's been working fine (so far...).

**Comment by Raphty** [comment]
I always use the password option.... but i will try the qc... It is just a bigger hassle then username and pw when you use a PWmanager, which is wehre I get the ip from as well 🤣

**Comment by extraslute** [comment]
I always use password also. I haven't changed how I've been logging in as a 4 year user. It does not sign out on Jellyfin for iOS nor Jellyfin for Android TV, nor on Roku -- only Apple TV. It happens everyday. Still happens everyday. At this point we're just used to it but wish

**Comment by Nicxe** [comment]
My wife asked me to switch to Plex instead, she was tired to log in everyday

**Comment by Raphty** [comment]
🤣 my said something similar yesterday as well (emby in our case)

**Comment by Nicxe** [comment]
I don´t even have the option to connect quick, the app does not find any server so need to enter that manually every time

**Comment by ScoobyDoo27** [comment]
I can’t do quick connect either. I run my server through docker and I believe that is the reason it doesn’t show up in the list of servers.

**Comment by adavidzh** [comment]
> I can’t do quick connect either. I run my server through docker and I believe that is the reason it doesn’t show up in the list of servers.

FWIW, my Jellyfin runs inside docker, shows up in the list of servers, and Quick Connect works. It's just not all that quick. (A QR code would be quicker.)

Still, the best would be for the credentials from logging in would be kept.

**Comment by Raphty** [comment]
I did try the "quick" login... it did not help. Next day I was logged out again. also I have to say that there is nothing quick about this... If you use a pw manager and your iphone to automatically put in the details that is 100times faster

still I have to say, I love the app!!! and I am super thankful ❤️

**Comment by JamesDearlove** [comment]
This issue finally got to me and I had some free time, so I went hunting to see if I could track down what is causing this and I might have found the problem. 

CoreStore stores its SQLite db in the `caches` directory on tvOS by default ([CoreStore doc link](https://johnestropia.github.io/CoreStore/index.html#setting-up:~:text=or%20the%20%E2%80%9CCaches/%E2%80%9D%20directory%20on%20tvOS)) and I think this gets swept up when tvOS does a cleanup when running low on space. There's no nice way to trigger this cleanup in the Simulator from what I understand, so I've deployed a fix onto my Apple TV and will see if this does actually fix it.

I've committed a patch to [my fork](https://github.com/jamesdearlove/Swiftfin/blob/main/Shared/Services/SwiftfinStore.swift#L202). If this fixes it, I'll open a PR.

**Comment by LePips** [comment]
Hey all, I've started debugging this and currently trying to replicate. If it is truly something that happens over a period of 24 hours, this might be tough.

**Comment by extraslute** [comment]
It is definitely something that happens over a 24 hour period. Probably the absolute most annoying thing I’ve ever experienced. And since my Jellyfin server is also part of my home assistant, every single time I have to login it creates a new “device” in home assistant so I have probably 60 Apple TVs showing but 59 of them inactive. I quit deleting them because it just continues to happen. 

On my bedroom Sony Bravia for the AndroidTV app I haven’t ever been signed out. 

If there's anything I can do to help you out let me know.

**Comment by Raphty** [comment]
I am not familiar with iOS/tvOS development, but I can help as well.

and interesting thing I had the last couple of days: when I have a video open when I leave the app, it keeps that video open over night, and I don't have to log in again (most days) but when I go back to the swiftfin overview, i think I am always logged out next evening (22h later most days 😃 )

**Comment by amochkin** [comment]
Apparently the issue can be fixed by using UserDefaults for storing API key.

**Comment by totally-a-human** [comment]
Using quick connect does not solve the problem.

As @JamesDearlove and @amochkin pointed out it seems like tvOS is very aggressive with purging data.

> Moreover, your app can only access 500 KB of persistent storage that is local to the device (using the [NSUserDefaults](https://developer.apple.com/library/archive/documentation/LegacyTechnologies/WebObjects/WebObjects_3.5/Reference/Frameworks/ObjC/Foundation/Classes/NSUserDefaults/Description.html#//apple_ref/occ/cl/NSUserDefaults) class). Outside of this limited local storage, all other data must be purgeable by the operating system when space is low.

That appears to be explaining why I'm not logged out of my Apple TV (as I don't use it too much) while someone I know is logged out much more often (and they use it a lot more). As far as I can see in the code the API key and the server details are [not stored in UserDefaults](https://github.com/jellyfin/Swiftfin/blob/34cd289106e4c15de0567efde54f8d22fe64f979/Shared/Services/SwiftfinStore.swift) so they are eligible for cleanup.

**Comment by LePips** [comment]
The API key is not stored in UserDefaults and never should be. I'm not too concerned with the cleanup being a problem as that is something that should have been an issue a long time ago, but it isn't out of the picture.

**Comment by Raphty** [comment]
2 days in a row I was not logged out while I keep the next video on pause and not Return to the main screen - but last night I did go back so I can report tomorrow if I got logged out again 😅

**Comment by Raphty** [comment]
Have not been logged out since the new tv os update. Maybe that fixed it?

**Comment by Jpkribs** [comment]
> Using quick connect does not solve the problem.
> 
> 
> 
> As @JamesDearlove and @amochkin pointed out it seems like tvOS is very aggressive with purging data.
> 
> 
> 
> > Moreover, your app can only access 500 KB of persistent storage that is local to the device (using the [NSUserDefaults](https://developer.apple.com/library/archive/documentation/LegacyTechnologies/WebObjects/WebObjects_3.5/Reference/Frameworks/ObjC/Foundation/Classes/NSUserDefaults/Description.html#//apple_ref/occ/cl/NSUserDefaults) class). Outside of this limited local storage, all other data must be purgeable by the operating system when space is low.
> 
> 
> 
> That appears to be explaining why I'm not logged out of my Apple TV (as I don't use it too much) while someone I know is logged out much more often (and they use it a lot more). As far as I can see in the code the API key and the server details are [not stored in UserDefaults](https://github.com/jellyfin/Swiftfin/blob/34cd289106e4c15de0567efde54f8d22fe64f979/Shared/Services/SwiftfinStore.swift) so they are eligible for cleanup.
> 
> 

Following up on this being a purging data on low storage, I was able to successfully recreate this issue.

I have a few thousand photos in iCloud. When I remove iCloud Photos from syncing to the Apple TV, I have a lot of free space and I rarely have Swiftfin logouts. When I re-enable iCloud Photos to sync, the Apple TV downloads images to get me to ~1gb free. The next time I open Swiftfin it requires me to log back in.

I assume this would work with anything that takes up a lot of storage on the AppleTV. I've found Infuse likes to chew up storage room too and I experience the same issue when Infuse takes up >5gb of library images. **In testing, it looks like when Swiftfin is not in the foreground and storage is low, credentials are lost.**

I hope this helps in testing/troubleshooting! Hopefully others are able to recreate this as well.

**Comment by jesuslopezreynosa** [comment]
I can replicate that the issue on tvOS 17 persists, and there is a new behaviour where it no longer accepts my credentials to log back into my media server.

**Comment by Nicxe** [comment]
> I can replicate that the issue on tvOS 17 persists, 

Same here, is seams to work for me know on TvOs17. Haven't ben logoed ut for a couple of days now

**Comment by extraslute** [comment]
This issue has seemingly disappeared on both of my Apple TVs. Gen 2 and 4 after the last time I did an update (Ubuntu). Used to kick me out every day -- does not do this anymore.

**Comment by pumax15** [comment]
I updated to the latest TV Os 17 and I still have the same problem. It keeps me logged in a little longer, but I still have to keep re-entering credentials.

**Comment by ioslife** [comment]
This problem made me switch to Infuse. I'd love to go back to Swiftfin, but this makes it unusable

**Comment by ioslife** [comment]
> > API keys are not stored in UserDefaults and never should be. I'm not too concerned with the cleanup being a problem as that is something that should have been an issue a long time ago, but it isn't out of the picture.
> 
> I disagree, using UserDefaults completely solves the problem. Can you please elaborate on why the app should never store API keys in UserDefaults?

API keys are typically considered private keys. UserDefaults stores data in a text file on the device. https://stackoverflow.com/questions/68022172/why-is-using-userdefaults-to-store-sensitive-information-on-ios-not-safe

**Comment by extraslute** [comment]
After updating to TVOS 17.1 -- this issue has came back. Logging out every single day at some point.

**Comment by zandr** [comment]
Is there a workaround that I'm missing here? I'm not sure how this isn't a showstopper. I haven't been able to configure a user that doesn't require a login, which disappears in a day or so.

**Comment by LePips** [comment]
Sadly there isn't a workaround. Frankly, this issue has been difficult for me because:

- I can barely reproduce it and I can't have a debugger (my laptop) running for days until I catch it
- I don't watch much nowadays so my server is barely on
- right now I'm more focused on getting iOS back to a state of release/polish because that's more manageable

So this issue is in the background for me, even though it can make the app practically unusable. I apologize for the inconvenience.

**Comment by zandr** [comment]
Thanks for the quick response! I was hoping there was some way to get an account to show up in the "Public Users" side of the login screen or similar, but it's not clear how to do that.

I've done exactly no tvOS development, but if you can point me at a guide to running the debugger, I actually could hang a spare machine off of one of our AppleTVs.

**Comment by Raphty** [comment]
> Have not been logged out since the new tv os update. Maybe that fixed it?

Since then I never got logged out again.

Maybe it is a different issue.

**Comment by imperialjoy** [comment]
Still happens to me.  Is there a way to use jellyfin in DLNA mode without logging in?  Is there a different way to store user credentials?  Or setup Jellyfin to not need credentials?  Seems like overkill for a LAN connection to the media server right beside the ATV.

**Comment by BDub38** [comment]
It has been some time since the last comment on this thread.  Has there been any progress or updates regarding this issue?  I am still experiencing this.  Sometimes it is daily or many days between the need to log in again.

**Comment by JPKribs** [comment]
This isn't a perfect fix, but it appears to happen when storage is low on the Apple TV. If you turn off the download screensaver option in the Apple TV settings and stop iCloud photos from syncing to the TV, it prevents the issue from occurring on my end. When I was doing some research it it sounds like Apple has a pretty aggressive cleanup process when storage starts getting low and Apple prioritizes retaining data from their own apps over third-party apps from the store so things like Infuse and Jellyfin have issues where the data gets wiped.

That being said, I think Jellyfin might be able to resolve this by moving how the credentials are stored? But I am absolutely not an expert, so I'll lean on more qualified people.

**Comment by RespectIsEverything** [comment]
Unaware if this issue is holding up the 1.1 update for tvos. I suspect most people would rather gain the updated device profile & pushback this bugfix for 1.2.

**Comment by PhilippeWeidmann** [comment]
Hi,

I took a look at this issue since I'm also having it on my Apple TV 😬 
It is fairly easy to reproduce in a simulator:
- Log the CoreStore location: 
For example in `setupDataStack` -> `Container.shared.logService().info("Created store @ \(storage.fileURL)")`
- Go to the location
- Delete the store

Deleting the store does the same as when tvOS cleans up the cache to free up space. 
Also, note that since the Swiftfin store is stored inside the `Cache` directory the same issue can also happen on iOS devices with low space. However, it will be less frequent since iOS is less aggressive with cache cleanup.

Now to fix the issue there are multiple solutions:
- Cache some mandatory models' data outside CoreData, eg. UserDefaults (from what I see it would be ServerModel and UserModel)
- Store strictly mandatory data alongside the token in the Keychain

**Cache outside CoreData**
This solution would fix the issue but, from what I understand in the code, this would defeat the purpose of caching to CoreData in the first place. Also, migrating models would be more difficult.

**Mandatory data alongside the token in the Keychain**
The idea is: if CoreData is empty, we check the Keychain. If the Keychain still contains data we use it to fetch the User/Server remotely. While we are doing this we display a simple loading view. If something fails we disconnect the user/remove the token.
Still from what I understand about Jellyfin / the app, the only missing information would be the server base URL. We could store it alongside the token.
With this solution, the whole app directory can be deleted and it would still recover from scratch using the Keychain.

This is an issue I've already been working on in one of my apps (We called it a `PreloadingView` -> https://github.com/Infomaniak/ios-kMail/blob/master/Mail/Views/PreloadingView.swift)

I'm still figuring out the whole architecture of the project but if you want me to, I'm willing to try to do some work on this issue using the second solution.

**Comment by foorschtbar** [comment]
Will there be a fix in the near future? It is very annoying that I need to login every time I opens Swiftfin on the ATV

**Comment by JPKribs** [comment]
Hey All,

~This should be resolved via [PR #1657](https://github.com/jellyfin/Swiftfin/pull/1657) and will be included in our next tvOS release.~ 

This release still has some additional work before it is ready but you can follow our progress here:

https://github.com/jellyfin/Swiftfin/discussions/1294

---

**EDIT:**

Apologies, this created some issues I missed in my tested and was reverted. Sorry for the fake out.

**Comment by ioslife** [comment]
Brutal. Looking forward to the future fix regardless. Thanks for your attempts @JPKribs!

**Comment by maxraywork** [comment]
Issue still persist and makes application UNUSABLE since it logout on every wake of tvOS.

Would be great getting back to this issue.
Thanks!

**Comment by PhilippeWeidmann** [comment]
Can't believe it's been more than a year since my comment 😬 

I had a couple of hours to take a look at this issue today 🎄 
I made a PR which should resolve it: https://github.com/jellyfin/Swiftfin/pull/1875

I'm looking for feedback as I'm not familiar with Swiftfin's architecture and also not a heavy user of Jellyfin.

**Comment by Nicxe** [comment]
Plex app on AppleTV do not have this issue so is it rely tvOS issue?

**Comment by LePips** [comment]
tvOS will now only use defaults storage in #1876
